### PR TITLE
servers give more modularity and flexibiltiy than importing classes

### PR DESCRIPTION
**Pull request by barbierluke**
- Change structure of classical cv code to group classical code into servers, allowing us to easily replace code without modification of source file or if statements deciding which class to import. 
- Create ClassicalBox2Pose.srv 
- Reimplement gate_localizer (midpoint method) to be a server.
Tested and confirmed, results do not vary from original implementation
- Implement skeleton of gate_pnp_color server
- Restructure localizer_node -> localizer_client to be a client for the classical cv servers
- Trash old code: 
1. localizer_node_old.py
2. dice_localizer.py
3. gate_localizer_pnp.py (although this contained a pixel analysis algorithm that we had previous success with, at the time I poorly wrote it to the point it is quite difficult to debug now, so I think it would be prudent to start over in a more modular approach. Future commit to follow. Old version used greyscale, possibly lose less information by converting to HSV, YUV or sticking with RGB? We will find out.

### CODE REVIEW

**Comment by barbierluke** [comment]
Here's the output of a rosmsg info on darknet_ros_msgs/BoundingBoxes:
std_msgs/Header header
  uint32 seq
  time stamp
  string frame_id
std_msgs/Header image_header
  uint32 seq
  time stamp
  string frame_id
darknet_ros_msgs/BoundingBox[] bounding_boxes
  string Class
  float64 probability
  int64 xmin
  int64 ymin
  int64 xmax
  int64 ymax
sensor_msgs/Image image
  std_msgs/Header header
    uint32 seq
    time stamp
    string frame_id
  uint32 height
  uint32 width
  string encoding
  uint8 is_bigendian
  uint32 step
  uint8[] data

Why are there 3 headers!?

**Comment by barbierluke** [comment]
Which one is the one I should use?

**Comment by DrYerzinia** [comment]
Yea the people who made darknet ros really didn't give a fuck about the header.

image_header/frame_id is the one with the correct data

**Comment by DrYerzinia** [comment]
Very happy, now when I turn on the image mux it will all work.

**Pull request merged**
